# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataflow_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64\x61taflow_manager.proto\x12\x10\x64\x61taflow_manager\"*\n\x18RequestGetTPRMNamesOfTMO\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x05\"+\n\x19ResponseGetTPRMNamesOfTMO\x12\x0e\n\x06\x63olumn\x18\x01 \x03(\t\"p\n\x1bRequestGetObjectsWithParams\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x05\x12\x12\n\ntprm_names\x18\x02 \x03(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x13\n\x06offset\x18\x04 \x01(\x05H\x00\x88\x01\x01\x42\t\n\x07_offset\",\n\x1cResponseGetObjectsWithParams\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"A\n\x1eRequestGetTPRMNameToTypeMapper\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x02 \x03(\t\"\x9f\x01\n\x1fResponseGetTPRMNameToTypeMapper\x12M\n\x06mapper\x18\x01 \x03(\x0b\x32=.dataflow_manager.ResponseGetTPRMNameToTypeMapper.MapperEntry\x1a-\n\x0bMapperEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xff\x02\n\x0f\x44\x61taflowManager\x12n\n\x11GetTPRMNamesOfTMO\x12*.dataflow_manager.RequestGetTPRMNamesOfTMO\x1a+.dataflow_manager.ResponseGetTPRMNamesOfTMO\"\x00\x12y\n\x14GetObjectsWithParams\x12-.dataflow_manager.RequestGetObjectsWithParams\x1a..dataflow_manager.ResponseGetObjectsWithParams\"\x00\x30\x01\x12\x80\x01\n\x17GetTPRMNameToTypeMapper\x12\x30.dataflow_manager.RequestGetTPRMNameToTypeMapper\x1a\x31.dataflow_manager.ResponseGetTPRMNameToTypeMapper\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataflow_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSEGETTPRMNAMETOTYPEMAPPER_MAPPERENTRY._options = None
  _RESPONSEGETTPRMNAMETOTYPEMAPPER_MAPPERENTRY._serialized_options = b'8\001'
  _REQUESTGETTPRMNAMESOFTMO._serialized_start=44
  _REQUESTGETTPRMNAMESOFTMO._serialized_end=86
  _RESPONSEGETTPRMNAMESOFTMO._serialized_start=88
  _RESPONSEGETTPRMNAMESOFTMO._serialized_end=131
  _REQUESTGETOBJECTSWITHPARAMS._serialized_start=133
  _REQUESTGETOBJECTSWITHPARAMS._serialized_end=245
  _RESPONSEGETOBJECTSWITHPARAMS._serialized_start=247
  _RESPONSEGETOBJECTSWITHPARAMS._serialized_end=291
  _REQUESTGETTPRMNAMETOTYPEMAPPER._serialized_start=293
  _REQUESTGETTPRMNAMETOTYPEMAPPER._serialized_end=358
  _RESPONSEGETTPRMNAMETOTYPEMAPPER._serialized_start=361
  _RESPONSEGETTPRMNAMETOTYPEMAPPER._serialized_end=520
  _RESPONSEGETTPRMNAMETOTYPEMAPPER_MAPPERENTRY._serialized_start=475
  _RESPONSEGETTPRMNAMETOTYPEMAPPER_MAPPERENTRY._serialized_end=520
  _DATAFLOWMANAGER._serialized_start=523
  _DATAFLOWMANAGER._serialized_end=906
# @@protoc_insertion_point(module_scope)
