"""Create document count of mo

Revision ID: 03fbe5d7245b
Revises: 773280660e16
Create Date: 2024-01-09 13:49:43.582651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '03fbe5d7245b'
down_revision = '773280660e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('document_count', sa.Integer(), nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo', 'document_count')
    # ### end Alembic commands ###
