"""lifecycle_process_definition not int, now is string

Revision ID: 093f5e296733
Revises: a683d8c78fcb
Create Date: 2023-07-13 16:35:44.342410

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '093f5e296733'
down_revision = 'a683d8c78fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmo', column_name='lifecycle_process_definition', type_=sa.String())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmo', column_name='lifecycle_process_definition', type_=sa.BigInteger(),
                    postgresql_using='lifecycle_process_definition::bigint')
    # ### end Alembic commands ###
