"""status field for tmo, mo added

Revision ID: 0b872b48f320
Revises: 31c1a0b65f6b
Create Date: 2023-02-03 09:26:18.976487

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b872b48f320'
down_revision = '31c1a0b65f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmo', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'status')
    op.drop_column('mo', 'status')
    # ### end Alembic commands ###
