"""trpm type field removed

Revision ID: 0ef251b85263
Revises: e984816c7e69
Create Date: 2022-08-10 16:42:25.373982

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0ef251b85263'
down_revision = 'e984816c7e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_tprm_tmo_id_type_name', 'tprm', type_='unique')
    op.create_unique_constraint('_tprm_tmo_id_name', 'tprm', ['tmo_id', 'name'])
    op.drop_column('tprm', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tprm', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('_tprm_tmo_id_name', 'tprm', type_='unique')
    op.create_unique_constraint('_tprm_tmo_id_type_name', 'tprm', ['tmo_id', 'type', 'name'])
    # ### end Alembic commands ###
