"""permissions

Revision ID: 0fb2c5eb05fa
Revises: 4747f0c46ab2
Create Date: 2023-04-07 17:43:00.653920

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '0fb2c5eb05fa'
down_revision = '4747f0c46ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmo_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tmo.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'permission')
    )
    op.create_index(op.f('ix_tmo_permission_parent_id'), 'tmo_permission', ['parent_id'], unique=False)
    op.create_table('mo_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['mo.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'permission')
    )
    op.create_index(op.f('ix_mo_permission_parent_id'), 'mo_permission', ['parent_id'], unique=False)
    op.create_table('tprm_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('create', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('update', sa.Boolean(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tprm.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'permission')
    )
    op.create_index(op.f('ix_tprm_permission_parent_id'), 'tprm_permission', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tprm_permission_parent_id'), table_name='tprm_permission')
    op.drop_table('tprm_permission')
    op.drop_index(op.f('ix_mo_permission_parent_id'), table_name='mo_permission')
    op.drop_table('mo_permission')
    op.drop_index(op.f('ix_tmo_permission_parent_id'), table_name='tmo_permission')
    op.drop_table('tmo_permission')
    # ### end Alembic commands ###
