"""Added cProfiler

Revision ID: 1e64cf435df2
Revises: 093f5e296733
Create Date: 2023-09-04 23:12:47.323497

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1e64cf435df2'
down_revision = '093f5e296733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('function_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_process', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
