"""Added lifecycle_process_definition to TMOBase

Revision ID: 21a0e15931f8
Revises: 328adb90f495
Create Date: 2023-07-04 15:26:43.031326

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '21a0e15931f8'
down_revision = '328adb90f495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('lifecycle_process_definition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'lifecycle_process_definition')
    # ### end Alembic commands ###
