"""update server_default document_count

Revision ID: 25b07f63e916
Revises: 61ab4c11a75e
Create Date: 2024-04-24 12:07:37.718551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '25b07f63e916'
down_revision = '61ab4c11a75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mo', 'document_count', server_default='0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
