"""add event index

Revision ID: 29b83250b3e6
Revises: bc558e60d1d7
Create Date: 2025-08-06 15:25:18.352275

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '29b83250b3e6'
down_revision = 'bc558e60d1d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_events_event_type_model_id',
        'events',
        ['event_type', 'model_id'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_event_type_model_id', table_name='events')
    # ### end Alembic commands ###
