"""Add severity id to tmo

Revision ID: 2b70b13e1b35
Revises: eb03a2f04455
Create Date: 2023-10-13 17:02:54.281182

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2b70b13e1b35'
down_revision = 'eb03a2f04455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('severity_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'severity_id')
    # ### end Alembic commands ###
