"""Added description for MO

Revision ID: 2f55103770ed
Revises: fea8af6b4aa9
Create Date: 2025-03-12 14:18:02.125363

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2f55103770ed'
down_revision = 'fea8af6b4aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo', 'description')
    # ### end Alembic commands ###
