"""security_default_values

Revision ID: 328adb90f495
Revises: def82a88cd9e
Create Date: 2023-06-12 18:08:52.245890

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '328adb90f495'
down_revision = 'def82a88cd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo_permission', sa.Column('permission_name', sa.String(), nullable=True))
    op.add_column('tmo_permission', sa.Column('permission_name', sa.String(), nullable=True))
    op.add_column('tprm_permission', sa.Column('permission_name', sa.String(), nullable=True))
    op.execute('''UPDATE mo_permission SET permission_name = REPLACE(permission, 'realm_access.__', '')''')
    op.execute('''UPDATE tmo_permission SET permission_name = REPLACE(permission, 'realm_access.__', '')''')
    op.execute('''UPDATE tprm_permission SET permission_name = REPLACE(permission, 'realm_access.__', '')''')
    op.alter_column('mo_permission', 'permission_name', nullable=False)
    op.alter_column('tmo_permission', 'permission_name', nullable=False)
    op.alter_column('tprm_permission', 'permission_name', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm_permission', 'permission_name')
    op.drop_column('tmo_permission', 'permission_name')
    op.drop_column('mo_permission', 'permission_name')
    # ### end Alembic commands ###
