"""primary field: tprm -> tmo

Revision ID: 3845fe0473b5
Revises: 766d0f883a79
Create Date: 2022-11-14 14:05:27.513681

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3845fe0473b5'
down_revision = '766d0f883a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('primary', sa.JSON(), nullable=False, server_default='[]'))
    op.alter_column('tprm', 'primary', server_default=None)
    op.drop_column('tprm', 'primary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tprm', sa.Column('primary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tmo', 'primary')
    # ### end Alembic commands ###
