"""Added indexes for TPRM

Revision ID: 3be10dc69b01
Revises: 2f55103770ed
Create Date: 2025-04-09 12:47:23.106825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3be10dc69b01'
down_revision = '2f55103770ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tprm_id'), 'tprm', ['id'], unique=False)
    op.create_index(op.f('ix_tprm_val_type'), 'tprm', ['val_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tprm_val_type'), table_name='tprm')
    op.drop_index(op.f('ix_tprm_id'), table_name='tprm')
    # ### end Alembic commands ###
