"""Revert

Revision ID: 422ad23caa58
Revises: 1e64cf435df2
Create Date: 2023-09-05 11:09:06.652935

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '422ad23caa58'
down_revision = '1e64cf435df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.create_table('test',
    sa.Column('function_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_process', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.create_table('test',
    sa.Column('function_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('time_process', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###