"""version field added for all models

Revision ID: 4747f0c46ab2
Revises: bd662242efe5
Create Date: 2023-02-06 13:16:28.254930

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4747f0c46ab2'
down_revision = 'bd662242efe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('version', sa.Integer(), nullable=False, server_default=str(1)))
    op.add_column('prm', sa.Column('version', sa.Integer(), nullable=False, server_default=str(1)))
    op.add_column('tmo', sa.Column('version', sa.Integer(), nullable=False, server_default=str(1)))
    op.add_column('tprm', sa.Column('version', sa.Integer(), nullable=False, server_default=str(1)))
    op.alter_column('mo', 'version', server_default=None)
    op.alter_column('prm', 'version', server_default=None)
    op.alter_column('tmo', 'version', server_default=None)
    op.alter_column('tprm', 'version', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'version')
    op.drop_column('tmo', 'version')
    op.drop_column('prm', 'version')
    op.drop_column('mo', 'version')
    # ### end Alembic commands ###
