"""tmo foreign keys update

Revision ID: 48604bf43683
Revises: 92e37b20bffe
Create Date: 2023-01-07 14:39:08.764790

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48604bf43683'
down_revision = '92e37b20bffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tmo', 'tmo', ['p_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tmo', type_='foreignkey')
    op.create_foreign_key('tmo_p_id_fkey', 'tmo', 'tmo', ['p_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
