"""mo active field added

Revision ID: 491ebd741cb9
Revises: 9dd5ff786c99
Create Date: 2022-10-07 18:03:43.063958

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '491ebd741cb9'
down_revision = '9dd5ff786c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('active', sa.Boolean(), nullable=False, server_default=str(True)))
    op.alter_column('mo', 'active', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo', 'active')
    # ### end Alembic commands ###
