"""added tmo lat, long, icon, description

Revision ID: 4cf9c76418ca
Revises: dbd1612cd391
Create Date: 2022-06-30 15:04:58.189970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4cf9c76418ca'
down_revision = 'dbd1612cd391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmo', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tmo', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('tmo', sa.Column('longitude', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'longitude')
    op.drop_column('tmo', 'latitude')
    op.drop_column('tmo', 'description')
    op.drop_column('tmo', 'icon')
    # ### end Alembic commands ###
