"""Remoed automation and searchable from TPRM attrs

Revision ID: 4f55d6dc5fef
Revises: bd6efac43134
Create Date: 2024-11-08 16:25:44.554493

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '4f55d6dc5fef'
down_revision = 'bd6efac43134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'searchable')
    op.drop_column('tprm', 'automation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tprm', sa.Column('searchable', sa.BOOLEAN(), nullable=True, server_default=None))
    op.add_column('tprm', sa.Column('automation', sa.BOOLEAN(), nullable=True, server_default=None))
    # ### end Alembic commands ###
