"""mo.model, tprm.automation fields added

Revision ID: 509359ed12e5
Revises: 6ecf73a22e8e
Create Date: 2022-08-30 13:25:18.500425

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '509359ed12e5'
down_revision = '6ecf73a22e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tprm', sa.Column('automation', sa.Boolean(), nullable=False, server_default=str(False)))
    op.alter_column('tprm', 'automation', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'automation')
    op.drop_column('mo', 'model')
    # ### end Alembic commands ###
