"""created label

Revision ID: 5def2623c78c
Revises: 5e89bb0d34a2
Create Date: 2024-07-02 17:21:14.861637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5def2623c78c'
down_revision = '5e89bb0d34a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('mo', sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_mo_label'), 'mo', ['label'], unique=False)
    op.add_column('tmo', sa.Column('label', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'label')
    op.drop_index(op.f('ix_mo_label'), table_name='mo')
    op.drop_column('mo', 'label')
    # ### end Alembic commands ###
