"""Add line_type to TMO

Revision ID: 61ab4c11a75e
Revises: 9efb474bc077
Create Date: 2024-04-16 14:40:12.945651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '61ab4c11a75e'
down_revision = '9efb474bc077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('line_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True,
                                   default=None))

    op.drop_column('tprm', 'line_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'line_type')
    # ### end Alembic commands ###
