"""basic migration

Revision ID: 6747c4484b14
Revises: 
Create Date: 2022-06-08 14:06:38.364358

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6747c4484b14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmo',
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['p_id'], ['tmo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='_tmo_name')
    )
    op.create_index(op.f('ix_tmo_name'), 'tmo', ['name'], unique=False)
    op.create_table('mo',
    sa.Column('tmo_id', sa.Integer(), nullable=True),
    sa.Column('p_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['mo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmo_id'], ['tmo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mo_name'), 'mo', ['name'], unique=False)
    op.create_table('tprm',
    sa.Column('tmo_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('val_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('constraint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tmo_id'], ['tmo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmo_id', 'type', 'name', name='_tprm_tmo_id_type_name')
    )
    op.create_index(op.f('ix_tprm_name'), 'tprm', ['name'], unique=False)
    op.create_table('prm',
    sa.Column('tprm_id', sa.Integer(), nullable=True),
    sa.Column('mo_id', sa.Integer(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['mo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tprm_id'], ['tprm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tprm_id', 'mo_id', name='_prm_tprm_id_mo_id')
    )
    op.create_index(op.f('ix_prm_value'), 'prm', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prm_value'), table_name='prm')
    op.drop_table('prm')
    op.drop_index(op.f('ix_tprm_name'), table_name='tprm')
    op.drop_table('tprm')
    op.drop_index(op.f('ix_mo_name'), table_name='mo')
    op.drop_table('mo')
    op.drop_index(op.f('ix_tmo_name'), table_name='tmo')
    op.drop_table('tmo')
    # ### end Alembic commands ###
