"""global uniqueness field added for tmo

Revision ID: 68e1a7869e88
Revises: ced2a567d03b
Create Date: 2022-12-19 18:11:13.968335

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '68e1a7869e88'
down_revision = 'ced2a567d03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('global_uniqueness', sa.Boolean(), nullable=False, server_default=str(True)))
    op.alter_column('tmo', 'global_uniqueness', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'global_uniqueness')
    # ### end Alembic commands ###
