"""pov, geometry fields for mo added

Revision ID: 6ecf73a22e8e
Revises: 0ef251b85263
Create Date: 2022-08-16 15:50:55.389088

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6ecf73a22e8e'
down_revision = '0ef251b85263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('pov', sa.JSON(), nullable=True))
    op.add_column('mo', sa.Column('geometry', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo', 'geometry')
    op.drop_column('mo', 'pov')
    # ### end Alembic commands ###
