"""Added points_constraint_by_tmo column for TMO

Revision ID: 7530dd108433
Revises: 2b70b13e1b35
Create Date: 2023-12-12 11:31:07.975467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7530dd108433'
down_revision = '2b70b13e1b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_event_time'), 'events', ['event_time'], unique=False)
    op.create_index(op.f('ix_events_model_id'), 'events', ['model_id'], unique=False)
    op.add_column('tmo', sa.Column('points_constraint_by_tmo', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'points_constraint_by_tmo')
    op.drop_index(op.f('ix_events_model_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_time'), table_name='events')
    # ### end Alembic commands ###
