"""prm_link_filter tprm field added

Revision ID: 766d0f883a79
Revises: 491ebd741cb9
Create Date: 2022-10-12 14:54:18.724466

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '766d0f883a79'
down_revision = '491ebd741cb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tprm', sa.Column('prm_link_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'prm_link_filter')
    # ### end Alembic commands ###
