"""field_type_column

Revision ID: 773280660e16
Revises: ef98975f9dd0
Create Date: 2023-12-22 12:20:20.267867

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '773280660e16'
down_revision = 'ef98975f9dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tprm', sa.Column('field_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'field_value')
    # ### end Alembic commands ###
