"""Added minimize field to TMO

Revision ID: 842f7c1666f0
Revises: 9b7a566d5fd8
Create Date: 2024-02-29 17:16:53.490470

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '842f7c1666f0'
down_revision = '9b7a566d5fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tmo', sa.Column('minimize', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'minimize')
    # ### end Alembic commands ###
