"""TMO_add_inherit_location_field

Revision ID: 8516d5d8f630
Revises: 03fbe5d7245b
Create Date: 2024-01-10 18:23:22.749477

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8516d5d8f630'
down_revision = '03fbe5d7245b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('tmo', sa.Column('inherit_location', sa.Boolean()))
    op.add_column('tmo', sa.Column('inherit_location', sa.Boolean(), nullable=True))
    op.execute(
        """
        UPDATE tmo
        SET inherit_location = False
        WHERE inherit_location is NULL;
        """
    )
    op.alter_column("tmo", "inherit_location", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tmo', 'inherit_location')
    # ### end Alembic commands ###
