"""mo foreign keys update

Revision ID: 92e37b20bffe
Revises: 68e1a7869e88
Create Date: 2023-01-07 14:21:39.640313

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92e37b20bffe'
down_revision = '68e1a7869e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mo_p_id_fkey', 'mo', type_='foreignkey')
    op.drop_constraint('mo_point_b_id_fkey', 'mo', type_='foreignkey')
    op.drop_constraint('mo_point_a_id_fkey', 'mo', type_='foreignkey')
    op.create_foreign_key(None, 'mo', 'mo', ['p_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'mo', 'mo', ['point_b_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'mo', 'mo', ['point_a_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.create_foreign_key('mo_point_a_id_fkey', 'mo', 'mo', ['point_a_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mo_point_b_id_fkey', 'mo', 'mo', ['point_b_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('mo_p_id_fkey', 'mo', 'mo', ['p_id'], ['id'])
    # ### end Alembic commands ###
