"""Update geometry null value

Revision ID: 92e76c14eef0
Revises: 8516d5d8f630
Create Date: 2024-01-29 19:44:05.044559

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '92e76c14eef0'
down_revision = '8516d5d8f630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE mo SET geometry = NULL WHERE geometry::varchar = 'null'""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
