"""Added indexing of main fields

Revision ID: 9b7a566d5fd8
Revises: a3218c76a73f
Create Date: 2024-02-29 10:33:38.650007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9b7a566d5fd8'
down_revision = 'a3218c76a73f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mo_p_id'), 'mo', ['p_id'], unique=False)
    op.create_index(op.f('ix_mo_point_a_id'), 'mo', ['point_a_id'], unique=False)
    op.create_index(op.f('ix_mo_point_b_id'), 'mo', ['point_b_id'], unique=False)
    op.create_index(op.f('ix_mo_tmo_id'), 'mo', ['tmo_id'], unique=False)
    op.create_index(op.f('ix_prm_mo_id'), 'prm', ['mo_id'], unique=False)
    op.create_index(op.f('ix_prm_tprm_id'), 'prm', ['tprm_id'], unique=False)
    op.create_index(op.f('ix_tprm_tmo_id'), 'tprm', ['tmo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tprm_tmo_id'), table_name='tprm')
    op.drop_index(op.f('ix_prm_tprm_id'), table_name='prm')
    op.drop_index(op.f('ix_prm_mo_id'), table_name='prm')
    op.drop_index(op.f('ix_mo_tmo_id'), table_name='mo')
    op.drop_index(op.f('ix_mo_point_b_id'), table_name='mo')
    op.drop_index(op.f('ix_mo_point_a_id'), table_name='mo')
    op.drop_index(op.f('ix_mo_p_id'), table_name='mo')
    # ### end Alembic commands ###
