"""event model added

Revision ID: 9dd5ff786c99
Revises: 509359ed12e5
Create Date: 2022-09-30 12:14:54.729407

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9dd5ff786c99'
down_revision = '509359ed12e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.Column('event', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='events_pkey')
                    )
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.drop_table('prmhistory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prmhistory',
    sa.Column('tprm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action_datetime', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['mo.id'], name='prmhistory_mo_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tprm_id'], ['tprm.id'], name='prmhistory_tprm_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='prmhistory_pkey')
    )

    op.drop_index('ix_events_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
