"""Add line_type for TPRM

Revision ID: 9efb474bc077
Revises: 842f7c1666f0
Create Date: 2024-04-11 15:06:36.954219

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '9efb474bc077'
down_revision = '842f7c1666f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tprm',
                  sa.Column('line_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'line_type')
    # ### end Alembic commands ###
