"""MO creation_date and modification_date default False

Revision ID: a3218c76a73f
Revises: 92e76c14eef0
Create Date: 2024-01-30 18:53:11.374380

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3218c76a73f'
down_revision = '92e76c14eef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE mo
        SET creation_date='2024-01-29 19:02:36.599323', modification_date='2024-01-29 19:02:36.599323'
        WHERE creation_date IS NULL OR modification_date IS NULL;""")

    op.alter_column('mo', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('mo', 'modification_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mo', 'modification_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('mo', 'creation_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
