"""Added lifecycle_process_definition

Revision ID: a683d8c78fcb
Revises: 21a0e15931f8
Create Date: 2023-07-05 12:59:08.585388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a683d8c78fcb'
down_revision = '21a0e15931f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmo', column_name='lifecycle_process_definition', type_=sa.BigInteger())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tmo', column_name='lifecycle_process_definition', type_=sa.Integer())
    # ### end Alembic commands ###
