"""Added deactivation datetime and state for session registry

Revision ID: bc558e60d1d7
Revises: 9d002a94e9bd
Create Date: 2025-04-24 11:13:48.842944

"""
from enum import Enum

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bc558e60d1d7'
down_revision = '9d002a94e9bd'
branch_labels = None
depends_on = None

class SessionRegistryStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    types = postgresql.ENUM(SessionRegistryStatus, name="session_registry_status")
    types.create(op.get_bind(), checkfirst=True)

    op.add_column('sessionregistry', sa.Column('deactivation_datetime', sa.DateTime(), nullable=True))
    op.add_column('sessionregistry', sa.Column('status', types, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessionregistry', 'status')
    op.drop_column('sessionregistry', 'deactivation_datetime')
    # ### end Alembic commands ###
