"""model id for history added

Revision ID: bd662242efe5
Revises: 0b872b48f320
Create Date: 2023-02-03 09:44:45.277221

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd662242efe5'
down_revision = '0b872b48f320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('model_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'model_id')
    # ### end Alembic commands ###
