"""created two_way mo_link

Revision ID: bd6efac43134
Revises: 5def2623c78c
Create Date: 2024-07-26 16:19:18.601927

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'bd6efac43134'
down_revision = '5def2623c78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prm', sa.Column('backward_link', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_prm_backward_link'), 'prm', ['backward_link'], unique=False)
    op.create_foreign_key('fk_prm_backward_link', 'prm', 'prm', ['backward_link'], ['id'], ondelete='CASCADE')
    op.add_column('tprm', sa.Column('backward_link', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tprm_backward_link'), 'tprm', ['backward_link'], unique=False)
    op.create_foreign_key('fk_tprm_backward_link', 'tprm', 'tprm', ['backward_link'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tprm_backward_link', 'tprm', type_='foreignkey')
    op.drop_index(op.f('ix_tprm_backward_link'), table_name='tprm')
    op.drop_column('tprm', 'backward_link')
    op.drop_constraint('fk_prm_backward_link', 'prm', type_='foreignkey')
    op.drop_index(op.f('ix_prm_backward_link'), table_name='prm')
    op.drop_column('prm', 'backward_link')
    # ### end Alembic commands ###
