"""point_a point_b cascade delete

Revision ID: ced2a567d03b
Revises: f3bd34ead99b
Create Date: 2022-12-13 16:16:40.708985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ced2a567d03b'
down_revision = 'f3bd34ead99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mo_point_b_id_fkey', 'mo', type_='foreignkey')
    op.drop_constraint('mo_point_a_id_fkey', 'mo', type_='foreignkey')
    op.create_foreign_key(None, 'mo', 'mo', ['point_b_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mo', 'mo', ['point_a_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.create_foreign_key('mo_point_a_id_fkey', 'mo', 'mo', ['point_a_id'], ['id'])
    op.create_foreign_key('mo_point_b_id_fkey', 'mo', 'mo', ['point_b_id'], ['id'])
    # ### end Alembic commands ###
