"""added param history model

Revision ID: dbd1612cd391
Revises: 6747c4484b14
Create Date: 2022-06-24 17:23:19.720517

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dbd1612cd391'
down_revision = '6747c4484b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prmhistory',
    sa.Column('tprm_id', sa.Integer(), nullable=True),
    sa.Column('mo_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_datetime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mo_id'], ['mo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tprm_id'], ['tprm.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prmhistory')
    # ### end Alembic commands ###
