"""root_permission

Revision ID: def82a88cd9e
Revises: 0fb2c5eb05fa
Create Date: 2023-06-08 11:13:51.672246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'def82a88cd9e'
down_revision = '0fb2c5eb05fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo_permission', sa.Column('root_permission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_mo_permission_root_permission_id'), 'mo_permission', ['root_permission_id'], unique=False)
    op.create_foreign_key(None, 'mo_permission', 'mo_permission', ['root_permission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('tmo_permission', sa.Column('root_permission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tmo_permission_root_permission_id'), 'tmo_permission', ['root_permission_id'], unique=False)
    op.create_foreign_key(None, 'tmo_permission', 'tmo_permission', ['root_permission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('tprm_permission', sa.Column('root_permission_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tprm_permission_root_permission_id'), 'tprm_permission', ['root_permission_id'], unique=False)
    op.create_foreign_key(None, 'tprm_permission', 'tprm_permission', ['root_permission_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tprm_permission', type_='foreignkey')
    op.drop_index(op.f('ix_tprm_permission_root_permission_id'), table_name='tprm_permission')
    op.drop_column('tprm_permission', 'root_permission_id')
    op.drop_constraint(None, 'tmo_permission', type_='foreignkey')
    op.drop_index(op.f('ix_tmo_permission_root_permission_id'), table_name='tmo_permission')
    op.drop_column('tmo_permission', 'root_permission_id')
    op.drop_constraint(None, 'mo_permission', type_='foreignkey')
    op.drop_index(op.f('ix_mo_permission_root_permission_id'), table_name='mo_permission')
    op.drop_column('mo_permission', 'root_permission_id')
    # ### end Alembic commands ###
