"""tprm, tmo, mo  model update

Revision ID: e984816c7e69
Revises: 4cf9c76418ca
Create Date: 2022-07-19 16:03:30.059185

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'e984816c7e69'
down_revision = '4cf9c76418ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('mo', sa.Column('longitude', sa.Float(), nullable=True))

    op.add_column('tmo', sa.Column('virtual', sa.Boolean(), nullable=False, server_default=str(False)))
    op.add_column('tmo', sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('tmo', sa.Column('modified_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))
    op.add_column('tmo', sa.Column('creation_date', sa.DateTime(), nullable=False, server_default=str(datetime.utcnow())))
    op.add_column('tmo', sa.Column('modification_date', sa.DateTime(), nullable=False, server_default=str(datetime.utcnow())))

    op.alter_column('tmo', 'virtual', server_default=None)
    op.alter_column('tmo', 'created_by', server_default=None)
    op.alter_column('tmo', 'modified_by', server_default=None)
    op.alter_column('tmo', 'creation_date', server_default=None)
    op.alter_column('tmo', 'modification_date', server_default=None)

    op.add_column('tprm', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tprm', sa.Column('searchable', sa.Boolean(), nullable=False, server_default=str(False)))
    op.add_column('tprm', sa.Column('returnable', sa.Boolean(), nullable=False, server_default=str(False)))
    op.add_column('tprm', sa.Column('created_by', sa.String(), nullable=False, server_default=''))
    op.add_column('tprm', sa.Column('modified_by', sa.String(), nullable=False, server_default=''))
    op.add_column('tprm', sa.Column('creation_date', sa.DateTime(), nullable=False, server_default=str(datetime.utcnow())))
    op.add_column('tprm', sa.Column('modification_date', sa.DateTime(), nullable=False, server_default=str(datetime.utcnow())))

    op.alter_column('tprm', 'created_by', server_default=None)
    op.alter_column('tprm', 'modified_by', server_default=None)
    op.alter_column('tprm', 'creation_date', server_default=None)
    op.alter_column('tprm', 'modification_date', server_default=None)
    op.alter_column('tprm', 'searchable', server_default=None)
    op.alter_column('tprm', 'returnable', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tprm', 'modification_date')
    op.drop_column('tprm', 'creation_date')
    op.drop_column('tprm', 'modified_by')
    op.drop_column('tprm', 'created_by')
    op.drop_column('tprm', 'returnable')
    op.drop_column('tprm', 'searchable')
    op.drop_column('tprm', 'description')
    op.drop_column('tmo', 'modification_date')
    op.drop_column('tmo', 'creation_date')
    op.drop_column('tmo', 'modified_by')
    op.drop_column('tmo', 'created_by')
    op.drop_column('tmo', 'virtual')
    op.drop_column('mo', 'longitude')
    op.drop_column('mo', 'latitude')
    # ### end Alembic commands ###
