"""Add call_time for test

Revision ID: eb03a2f04455
Revises: f89817487e04
Create Date: 2023-10-07 18:18:58.285208

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'eb03a2f04455'
down_revision = 'f89817487e04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('call_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'call_time')
    # ### end Alembic commands ###
