"""Add null true for creation date and modification date for MO

Revision ID: ef98975f9dd0
Revises: a56eb2f191fa
Create Date: 2023-12-21 12:18:33.992858

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef98975f9dd0'
down_revision = '7530dd108433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('creation_date', sa.DateTime(), nullable=True))
    op.add_column('mo', sa.Column('modification_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo', 'modification_date')
    op.drop_column('mo', 'creation_date')
    # ### end Alembic commands ###
