"""point a, point b added to mo model

Revision ID: f3bd34ead99b
Revises: 3845fe0473b5
Create Date: 2022-12-06 14:52:58.183127

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3bd34ead99b'
down_revision = '3845fe0473b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo', sa.Column('point_a_id', sa.Integer(), nullable=True))
    op.add_column('mo', sa.Column('point_b_id', sa.Integer(), nullable=True))
    op.drop_constraint('mo_p_id_fkey', 'mo', type_='foreignkey')
    op.create_foreign_key(None, 'mo', 'mo', ['point_a_id'], ['id'])
    op.create_foreign_key(None, 'mo', 'mo', ['point_b_id'], ['id'])
    op.create_foreign_key(None, 'mo', 'mo', ['p_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.drop_constraint(None, 'mo', type_='foreignkey')
    op.create_foreign_key('mo_p_id_fkey', 'mo', 'mo', ['p_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mo', 'point_b_id')
    op.drop_column('mo', 'point_a_id')
    # ### end Alembic commands ###
