"""update all doucment count from null to zero

Revision ID: f6dc4fdfcaa6
Revises: 25b07f63e916
Create Date: 2024-04-24 12:10:17.407754

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f6dc4fdfcaa6'
down_revision = '25b07f63e916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""UPDATE mo SET document_count = 0 WHERE document_count is null""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
