"""added background task model

Revision ID: fea8af6b4aa9
Revises: 4f55d6dc5fef
Create Date: 2025-01-30 13:54:20.630153

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fea8af6b4aa9'
down_revision = '4f55d6dc5fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backgroundtask',
    sa.Column('object_type_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['tmo.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_backgroundtask_object_type_id'), 'backgroundtask', ['object_type_id'], unique=False)
    op.alter_column('tprm', 'multiple',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tprm', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tprm', 'required',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('tprm', 'multiple',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_backgroundtask_object_type_id'), table_name='backgroundtask')
    op.drop_table('backgroundtask')
    # ### end Alembic commands ###
