# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import airflow_manager_pb2 as airflow__manager__pb2


class AirflowManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchImport = channel.stream_unary(
                '/inventory.AirflowManager/BatchImport',
                request_serializer=airflow__manager__pb2.RequestBatchImport.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseBatchImport.FromString,
                )
        self.BatchExport = channel.unary_stream(
                '/inventory.AirflowManager/BatchExport',
                request_serializer=airflow__manager__pb2.RequestBatchExport.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseBatchExport.FromString,
                )
        self.CreateTMOorGetInfo = channel.unary_unary(
                '/inventory.AirflowManager/CreateTMOorGetInfo',
                request_serializer=airflow__manager__pb2.RequestCreateTMOOrGetInfo.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseCreateTMOOrGetInfo.FromString,
                )
        self.CreateTPRMsForTMO = channel.unary_unary(
                '/inventory.AirflowManager/CreateTPRMsForTMO',
                request_serializer=airflow__manager__pb2.RequestCreateTPRMsForTMO.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseCreateTPRMsForTMO.FromString,
                )
        self.DeleteAllObjectsInTMO = channel.unary_unary(
                '/inventory.AirflowManager/DeleteAllObjectsInTMO',
                request_serializer=airflow__manager__pb2.RequestDeleteAllObjects.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseDeleteAllObjects.FromString,
                )
        self.GetTMOName = channel.unary_unary(
                '/inventory.AirflowManager/GetTMOName',
                request_serializer=airflow__manager__pb2.RequestGetTMOName.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseGetTMOName.FromString,
                )
        self.GetTPRMNamesByIds = channel.unary_unary(
                '/inventory.AirflowManager/GetTPRMNamesByIds',
                request_serializer=airflow__manager__pb2.RequestGetTPRMNamesByIds.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseGetTPRMNamesByIds.FromString,
                )
        self.GetRequiredFields = channel.unary_unary(
                '/inventory.AirflowManager/GetRequiredFields',
                request_serializer=airflow__manager__pb2.RequestGetRequiredFields.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseGetRequiredFields.FromString,
                )
        self.GetMOAttrsAndTPRMs = channel.unary_unary(
                '/inventory.AirflowManager/GetMOAttrsAndTPRMs',
                request_serializer=airflow__manager__pb2.RequestGetMOAttrsAndTPRMs.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseGetMOAttrsAndTPRMs.FromString,
                )
        self.GetTMOLocations = channel.unary_stream(
                '/inventory.AirflowManager/GetTMOLocations',
                request_serializer=airflow__manager__pb2.RequestGetTMOLocations.SerializeToString,
                response_deserializer=airflow__manager__pb2.ResponseGetTMOLocations.FromString,
                )


class AirflowManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BatchImport(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchExport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTMOorGetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTPRMsForTMO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAllObjectsInTMO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPRMNamesByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequiredFields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOAttrsAndTPRMs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOLocations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirflowManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchImport': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchImport,
                    request_deserializer=airflow__manager__pb2.RequestBatchImport.FromString,
                    response_serializer=airflow__manager__pb2.ResponseBatchImport.SerializeToString,
            ),
            'BatchExport': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchExport,
                    request_deserializer=airflow__manager__pb2.RequestBatchExport.FromString,
                    response_serializer=airflow__manager__pb2.ResponseBatchExport.SerializeToString,
            ),
            'CreateTMOorGetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTMOorGetInfo,
                    request_deserializer=airflow__manager__pb2.RequestCreateTMOOrGetInfo.FromString,
                    response_serializer=airflow__manager__pb2.ResponseCreateTMOOrGetInfo.SerializeToString,
            ),
            'CreateTPRMsForTMO': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTPRMsForTMO,
                    request_deserializer=airflow__manager__pb2.RequestCreateTPRMsForTMO.FromString,
                    response_serializer=airflow__manager__pb2.ResponseCreateTPRMsForTMO.SerializeToString,
            ),
            'DeleteAllObjectsInTMO': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAllObjectsInTMO,
                    request_deserializer=airflow__manager__pb2.RequestDeleteAllObjects.FromString,
                    response_serializer=airflow__manager__pb2.ResponseDeleteAllObjects.SerializeToString,
            ),
            'GetTMOName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOName,
                    request_deserializer=airflow__manager__pb2.RequestGetTMOName.FromString,
                    response_serializer=airflow__manager__pb2.ResponseGetTMOName.SerializeToString,
            ),
            'GetTPRMNamesByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTPRMNamesByIds,
                    request_deserializer=airflow__manager__pb2.RequestGetTPRMNamesByIds.FromString,
                    response_serializer=airflow__manager__pb2.ResponseGetTPRMNamesByIds.SerializeToString,
            ),
            'GetRequiredFields': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequiredFields,
                    request_deserializer=airflow__manager__pb2.RequestGetRequiredFields.FromString,
                    response_serializer=airflow__manager__pb2.ResponseGetRequiredFields.SerializeToString,
            ),
            'GetMOAttrsAndTPRMs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMOAttrsAndTPRMs,
                    request_deserializer=airflow__manager__pb2.RequestGetMOAttrsAndTPRMs.FromString,
                    response_serializer=airflow__manager__pb2.ResponseGetMOAttrsAndTPRMs.SerializeToString,
            ),
            'GetTMOLocations': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTMOLocations,
                    request_deserializer=airflow__manager__pb2.RequestGetTMOLocations.FromString,
                    response_serializer=airflow__manager__pb2.ResponseGetTMOLocations.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.AirflowManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AirflowManager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BatchImport(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/inventory.AirflowManager/BatchImport',
            airflow__manager__pb2.RequestBatchImport.SerializeToString,
            airflow__manager__pb2.ResponseBatchImport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchExport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/inventory.AirflowManager/BatchExport',
            airflow__manager__pb2.RequestBatchExport.SerializeToString,
            airflow__manager__pb2.ResponseBatchExport.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTMOorGetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/CreateTMOorGetInfo',
            airflow__manager__pb2.RequestCreateTMOOrGetInfo.SerializeToString,
            airflow__manager__pb2.ResponseCreateTMOOrGetInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTPRMsForTMO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/CreateTPRMsForTMO',
            airflow__manager__pb2.RequestCreateTPRMsForTMO.SerializeToString,
            airflow__manager__pb2.ResponseCreateTPRMsForTMO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteAllObjectsInTMO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/DeleteAllObjectsInTMO',
            airflow__manager__pb2.RequestDeleteAllObjects.SerializeToString,
            airflow__manager__pb2.ResponseDeleteAllObjects.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/GetTMOName',
            airflow__manager__pb2.RequestGetTMOName.SerializeToString,
            airflow__manager__pb2.ResponseGetTMOName.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPRMNamesByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/GetTPRMNamesByIds',
            airflow__manager__pb2.RequestGetTPRMNamesByIds.SerializeToString,
            airflow__manager__pb2.ResponseGetTPRMNamesByIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRequiredFields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/GetRequiredFields',
            airflow__manager__pb2.RequestGetRequiredFields.SerializeToString,
            airflow__manager__pb2.ResponseGetRequiredFields.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOAttrsAndTPRMs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inventory.AirflowManager/GetMOAttrsAndTPRMs',
            airflow__manager__pb2.RequestGetMOAttrsAndTPRMs.SerializeToString,
            airflow__manager__pb2.ResponseGetMOAttrsAndTPRMs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/inventory.AirflowManager/GetTMOLocations',
            airflow__manager__pb2.RequestGetTMOLocations.SerializeToString,
            airflow__manager__pb2.ResponseGetTMOLocations.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
