# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65vent_manager.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n\x0fNewEventRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x15\n\rinstance_name\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"7\n\x10NewEventResponse\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2M\n\x14\x45ventManagerInformer\x12\x35\n\x08NewEvent\x12\x10.NewEventRequest\x1a\x11.NewEventResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_manager_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NEWEVENTREQUEST']._serialized_start=113
  _globals['_NEWEVENTREQUEST']._serialized_end=181
  _globals['_NEWEVENTRESPONSE']._serialized_start=183
  _globals['_NEWEVENTRESPONSE']._serialized_end=238
  _globals['_EVENTMANAGERINFORMER']._serialized_start=240
  _globals['_EVENTMANAGERINFORMER']._serialized_end=317
# @@protoc_insertion_point(module_scope)
