# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import event_manager_pb2 as event__manager__pb2


class EventManagerInformerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewEvent = channel.stream_stream(
                '/EventManagerInformer/NewEvent',
                request_serializer=event__manager__pb2.NewEventRequest.SerializeToString,
                response_deserializer=event__manager__pb2.NewEventResponse.FromString,
                )


class EventManagerInformerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewEvent(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventManagerInformerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewEvent': grpc.stream_stream_rpc_method_handler(
                    servicer.NewEvent,
                    request_deserializer=event__manager__pb2.NewEventRequest.FromString,
                    response_serializer=event__manager__pb2.NewEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'EventManagerInformer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EventManagerInformer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewEvent(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/EventManagerInformer/NewEvent',
            event__manager__pb2.NewEventRequest.SerializeToString,
            event__manager__pb2.NewEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
