# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import zeebe_to_inventory_pb2 as zeebe__to__inventory__pb2


class ZeebeInformerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadObjectTypes = channel.unary_unary(
                '/zeebe_client.ZeebeInformer/ReadObjectTypes',
                request_serializer=zeebe__to__inventory__pb2.InReadObjectTypes.SerializeToString,
                response_deserializer=zeebe__to__inventory__pb2.OutTMOArray.FromString,
                )
        self.ReadObjects = channel.unary_unary(
                '/zeebe_client.ZeebeInformer/ReadObjects',
                request_serializer=zeebe__to__inventory__pb2.InReadObjects.SerializeToString,
                response_deserializer=zeebe__to__inventory__pb2.OutMOArray.FromString,
                )
        self.ReadObjectTypeParamTypes = channel.unary_unary(
                '/zeebe_client.ZeebeInformer/ReadObjectTypeParamTypes',
                request_serializer=zeebe__to__inventory__pb2.InReadObjectTypeParamTypes.SerializeToString,
                response_deserializer=zeebe__to__inventory__pb2.OutTPRMArray.FromString,
                )
        self.UpdateObjectType = channel.unary_unary(
                '/zeebe_client.ZeebeInformer/UpdateObjectType',
                request_serializer=zeebe__to__inventory__pb2.InUpdateObjectType.SerializeToString,
                response_deserializer=zeebe__to__inventory__pb2.TMO.FromString,
                )
        self.ReadChildObjectTypes = channel.unary_unary(
                '/zeebe_client.ZeebeInformer/ReadChildObjectTypes',
                request_serializer=zeebe__to__inventory__pb2.InReadChildObjectTypes.SerializeToString,
                response_deserializer=zeebe__to__inventory__pb2.OutTMOArray.FromString,
                )
        self.GetTMOIdsByMoIds = channel.unary_unary(
                '/zeebe_client.ZeebeInformer/GetTMOIdsByMoIds',
                request_serializer=zeebe__to__inventory__pb2.InGetTMOIdsByMoIds.SerializeToString,
                response_deserializer=zeebe__to__inventory__pb2.OutGetTMOIdsByMoIds.FromString,
                )


class ZeebeInformerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadObjectTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadObjectTypeParamTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateObjectType(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadChildObjectTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTMOIdsByMoIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZeebeInformerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadObjectTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadObjectTypes,
                    request_deserializer=zeebe__to__inventory__pb2.InReadObjectTypes.FromString,
                    response_serializer=zeebe__to__inventory__pb2.OutTMOArray.SerializeToString,
            ),
            'ReadObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadObjects,
                    request_deserializer=zeebe__to__inventory__pb2.InReadObjects.FromString,
                    response_serializer=zeebe__to__inventory__pb2.OutMOArray.SerializeToString,
            ),
            'ReadObjectTypeParamTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadObjectTypeParamTypes,
                    request_deserializer=zeebe__to__inventory__pb2.InReadObjectTypeParamTypes.FromString,
                    response_serializer=zeebe__to__inventory__pb2.OutTPRMArray.SerializeToString,
            ),
            'UpdateObjectType': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateObjectType,
                    request_deserializer=zeebe__to__inventory__pb2.InUpdateObjectType.FromString,
                    response_serializer=zeebe__to__inventory__pb2.TMO.SerializeToString,
            ),
            'ReadChildObjectTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChildObjectTypes,
                    request_deserializer=zeebe__to__inventory__pb2.InReadChildObjectTypes.FromString,
                    response_serializer=zeebe__to__inventory__pb2.OutTMOArray.SerializeToString,
            ),
            'GetTMOIdsByMoIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOIdsByMoIds,
                    request_deserializer=zeebe__to__inventory__pb2.InGetTMOIdsByMoIds.FromString,
                    response_serializer=zeebe__to__inventory__pb2.OutGetTMOIdsByMoIds.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeebe_client.ZeebeInformer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ZeebeInformer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadObjectTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe_client.ZeebeInformer/ReadObjectTypes',
            zeebe__to__inventory__pb2.InReadObjectTypes.SerializeToString,
            zeebe__to__inventory__pb2.OutTMOArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe_client.ZeebeInformer/ReadObjects',
            zeebe__to__inventory__pb2.InReadObjects.SerializeToString,
            zeebe__to__inventory__pb2.OutMOArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadObjectTypeParamTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe_client.ZeebeInformer/ReadObjectTypeParamTypes',
            zeebe__to__inventory__pb2.InReadObjectTypeParamTypes.SerializeToString,
            zeebe__to__inventory__pb2.OutTPRMArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateObjectType(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe_client.ZeebeInformer/UpdateObjectType',
            zeebe__to__inventory__pb2.InUpdateObjectType.SerializeToString,
            zeebe__to__inventory__pb2.TMO.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadChildObjectTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe_client.ZeebeInformer/ReadChildObjectTypes',
            zeebe__to__inventory__pb2.InReadChildObjectTypes.SerializeToString,
            zeebe__to__inventory__pb2.OutTMOArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTMOIdsByMoIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe_client.ZeebeInformer/GetTMOIdsByMoIds',
            zeebe__to__inventory__pb2.InGetTMOIdsByMoIds.SerializeToString,
            zeebe__to__inventory__pb2.OutGetTMOIdsByMoIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
