# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import zeebe_severity_pb2 as zeebe__severity__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in zeebe_severity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class SeverityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeverityByFilters = channel.unary_unary(
                '/zeebe.severity.Severity/GetSeverityByFilters',
                request_serializer=zeebe__severity__pb2.FilterInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ListResponseSeverity.FromString,
                _registered_method=True)
        self.GetSeverityByRanges = channel.unary_unary(
                '/zeebe.severity.Severity/GetSeverityByRanges',
                request_serializer=zeebe__severity__pb2.ByRangesInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ListResponseSeverity.FromString,
                _registered_method=True)
        self.GetProcesses = channel.unary_unary(
                '/zeebe.severity.Severity/GetProcesses',
                request_serializer=zeebe__severity__pb2.ProcessesInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ProcessesResponse.FromString,
                _registered_method=True)
        self.GetSeverityByHierarchy = channel.unary_unary(
                '/zeebe.severity.Severity/GetSeverityByHierarchy',
                request_serializer=zeebe__severity__pb2.ByHierarchyInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ListResponseSeverity.FromString,
                _registered_method=True)
        self.GetProcessInstanceForSpecialTMO = channel.unary_stream(
                '/zeebe.severity.Severity/GetProcessInstanceForSpecialTMO',
                request_serializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMORequest.SerializeToString,
                response_deserializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMOResponse.FromString,
                _registered_method=True)
        self.GetChildObjectsWithProcessInstance = channel.unary_stream(
                '/zeebe.severity.Severity/GetChildObjectsWithProcessInstance',
                request_serializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceRequest.SerializeToString,
                response_deserializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceResponse.FromString,
                _registered_method=True)
        self.CheckLifecycleProcessDefinitionExists = channel.unary_unary(
                '/zeebe.severity.Severity/CheckLifecycleProcessDefinitionExists',
                request_serializer=zeebe__severity__pb2.CheckLifecycleProcessDefinitionExistsRequest.SerializeToString,
                response_deserializer=zeebe__severity__pb2.CheckLifecycleProcessDefinitionExistsResponse.FromString,
                _registered_method=True)


class SeverityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSeverityByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeverityByRanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeverityByHierarchy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessInstanceForSpecialTMO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildObjectsWithProcessInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckLifecycleProcessDefinitionExists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeverityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeverityByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByFilters,
                    request_deserializer=zeebe__severity__pb2.FilterInput.FromString,
                    response_serializer=zeebe__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetSeverityByRanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByRanges,
                    request_deserializer=zeebe__severity__pb2.ByRangesInput.FromString,
                    response_serializer=zeebe__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcesses,
                    request_deserializer=zeebe__severity__pb2.ProcessesInput.FromString,
                    response_serializer=zeebe__severity__pb2.ProcessesResponse.SerializeToString,
            ),
            'GetSeverityByHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByHierarchy,
                    request_deserializer=zeebe__severity__pb2.ByHierarchyInput.FromString,
                    response_serializer=zeebe__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetProcessInstanceForSpecialTMO': grpc.unary_stream_rpc_method_handler(
                    servicer.GetProcessInstanceForSpecialTMO,
                    request_deserializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMORequest.FromString,
                    response_serializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMOResponse.SerializeToString,
            ),
            'GetChildObjectsWithProcessInstance': grpc.unary_stream_rpc_method_handler(
                    servicer.GetChildObjectsWithProcessInstance,
                    request_deserializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceRequest.FromString,
                    response_serializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceResponse.SerializeToString,
            ),
            'CheckLifecycleProcessDefinitionExists': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLifecycleProcessDefinitionExists,
                    request_deserializer=zeebe__severity__pb2.CheckLifecycleProcessDefinitionExistsRequest.FromString,
                    response_serializer=zeebe__severity__pb2.CheckLifecycleProcessDefinitionExistsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeebe.severity.Severity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zeebe.severity.Severity', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Severity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSeverityByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeebe.severity.Severity/GetSeverityByFilters',
            zeebe__severity__pb2.FilterInput.SerializeToString,
            zeebe__severity__pb2.ListResponseSeverity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeverityByRanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeebe.severity.Severity/GetSeverityByRanges',
            zeebe__severity__pb2.ByRangesInput.SerializeToString,
            zeebe__severity__pb2.ListResponseSeverity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeebe.severity.Severity/GetProcesses',
            zeebe__severity__pb2.ProcessesInput.SerializeToString,
            zeebe__severity__pb2.ProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeverityByHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeebe.severity.Severity/GetSeverityByHierarchy',
            zeebe__severity__pb2.ByHierarchyInput.SerializeToString,
            zeebe__severity__pb2.ListResponseSeverity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessInstanceForSpecialTMO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/zeebe.severity.Severity/GetProcessInstanceForSpecialTMO',
            zeebe__severity__pb2.GetProcessInstanceForSpecialTMORequest.SerializeToString,
            zeebe__severity__pb2.GetProcessInstanceForSpecialTMOResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildObjectsWithProcessInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/zeebe.severity.Severity/GetChildObjectsWithProcessInstance',
            zeebe__severity__pb2.GetChildObjectsWithProcessInstanceRequest.SerializeToString,
            zeebe__severity__pb2.GetChildObjectsWithProcessInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckLifecycleProcessDefinitionExists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeebe.severity.Severity/CheckLifecycleProcessDefinitionExists',
            zeebe__severity__pb2.CheckLifecycleProcessDefinitionExistsRequest.SerializeToString,
            zeebe__severity__pb2.CheckLifecycleProcessDefinitionExistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
