# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dataview_to_inventory_pb2 as dataview__to__inventory__pb2


class DataviewToInventoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMOByTMOIdForView = channel.unary_stream(
                '/dataview_to_inventory.DataviewToInventory/GetMOByTMOIdForView',
                request_serializer=dataview__to__inventory__pb2.GetMOByTMOIdForViewRequest.SerializeToString,
                response_deserializer=dataview__to__inventory__pb2.GetMOByTMOIdForViewResponse.FromString,
                )


class DataviewToInventoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMOByTMOIdForView(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataviewToInventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMOByTMOIdForView': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMOByTMOIdForView,
                    request_deserializer=dataview__to__inventory__pb2.GetMOByTMOIdForViewRequest.FromString,
                    response_serializer=dataview__to__inventory__pb2.GetMOByTMOIdForViewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataview_to_inventory.DataviewToInventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataviewToInventory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMOByTMOIdForView(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/dataview_to_inventory.DataviewToInventory/GetMOByTMOIdForView',
            dataview__to__inventory__pb2.GetMOByTMOIdForViewRequest.SerializeToString,
            dataview__to__inventory__pb2.GetMOByTMOIdForViewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
