# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dataview_to_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64\x61taview_to_inventory.proto\x12\x15\x64\x61taview_to_inventory\"Z\n\x1aGetMOByTMOIdForViewRequest\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x05\x12\x1a\n\rreplace_links\x18\x02 \x01(\x08H\x00\x88\x01\x01\x42\x10\n\x0e_replace_links\"6\n\x1bGetMOByTMOIdForViewResponse\x12\x17\n\x0fmos_with_params\x18\x01 \x03(\t2\x98\x01\n\x13\x44\x61taviewToInventory\x12\x80\x01\n\x13GetMOByTMOIdForView\x12\x31.dataview_to_inventory.GetMOByTMOIdForViewRequest\x1a\x32.dataview_to_inventory.GetMOByTMOIdForViewResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dataview_to_inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMOBYTMOIDFORVIEWREQUEST._serialized_start=54
  _GETMOBYTMOIDFORVIEWREQUEST._serialized_end=144
  _GETMOBYTMOIDFORVIEWRESPONSE._serialized_start=146
  _GETMOBYTMOIDFORVIEWRESPONSE._serialized_end=200
  _DATAVIEWTOINVENTORY._serialized_start=203
  _DATAVIEWTOINVENTORY._serialized_end=355
# @@protoc_insertion_point(module_scope)
