# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15tasks_inventory.proto\x12\x0ftasks_inventory\"\xac\x01\n\x1d\x43reateObjectWithParamsRequest\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x03\x12\x0c\n\x04p_id\x18\x02 \x01(\x03\x12\x12\n\npoint_a_id\x18\x03 \x01(\x03\x12\x12\n\npoint_b_id\x18\x04 \x01(\x03\x12\x0b\n\x03pov\x18\x05 \x01(\t\x12\x10\n\x08geometry\x18\x06 \x01(\t\x12&\n\x06params\x18\x07 \x03(\x0b\x32\x16.tasks_inventory.Param\"\'\n\x05Param\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0f\n\x07tprm_id\x18\x02 \x01(\x05\" \n\x1e\x43reateObjectWithParamsResponse2\x8b\x01\n\x0eTasksInventory\x12y\n\x16\x43reateObjectWithParams\x12..tasks_inventory.CreateObjectWithParamsRequest\x1a/.tasks_inventory.CreateObjectWithParamsResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEOBJECTWITHPARAMSREQUEST._serialized_start=43
  _CREATEOBJECTWITHPARAMSREQUEST._serialized_end=215
  _PARAM._serialized_start=217
  _PARAM._serialized_end=256
  _CREATEOBJECTWITHPARAMSRESPONSE._serialized_start=258
  _CREATEOBJECTWITHPARAMSRESPONSE._serialized_end=290
  _TASKSINVENTORY._serialized_start=293
  _TASKSINVENTORY._serialized_end=432
# @@protoc_insertion_point(module_scope)
