# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import tasks_inventory_pb2 as tasks__inventory__pb2


class TasksInventoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateObjectWithParams = channel.unary_unary(
                '/tasks_inventory.TasksInventory/CreateObjectWithParams',
                request_serializer=tasks__inventory__pb2.CreateObjectWithParamsRequest.SerializeToString,
                response_deserializer=tasks__inventory__pb2.CreateObjectWithParamsResponse.FromString,
                )


class TasksInventoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateObjectWithParams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TasksInventoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateObjectWithParams': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateObjectWithParams,
                    request_deserializer=tasks__inventory__pb2.CreateObjectWithParamsRequest.FromString,
                    response_serializer=tasks__inventory__pb2.CreateObjectWithParamsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tasks_inventory.TasksInventory', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TasksInventory(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateObjectWithParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tasks_inventory.TasksInventory/CreateObjectWithParams',
            tasks__inventory__pb2.CreateObjectWithParamsRequest.SerializeToString,
            tasks__inventory__pb2.CreateObjectWithParamsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
