# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import documents_pb2 as documents__pb2


class DocumentInformerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetObjectDocumentCount = channel.unary_stream(
                '/documents.DocumentInformer/GetObjectDocumentCount',
                request_serializer=documents__pb2.RequestGetObjectDocumentCount.SerializeToString,
                response_deserializer=documents__pb2.ResponseGetObjectDocumentCount.FromString,
                )


class DocumentInformerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetObjectDocumentCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentInformerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetObjectDocumentCount': grpc.unary_stream_rpc_method_handler(
                    servicer.GetObjectDocumentCount,
                    request_deserializer=documents__pb2.RequestGetObjectDocumentCount.FromString,
                    response_serializer=documents__pb2.ResponseGetObjectDocumentCount.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'documents.DocumentInformer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocumentInformer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetObjectDocumentCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/documents.DocumentInformer/GetObjectDocumentCount',
            documents__pb2.RequestGetObjectDocumentCount.SerializeToString,
            documents__pb2.ResponseGetObjectDocumentCount.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
