# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: documents.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64ocuments.proto\x12\tdocuments\".\n\x1dRequestGetObjectDocumentCount\x12\r\n\x05\x63heck\x18\x01 \x01(\x08\"\xbc\x01\n\x1eResponseGetObjectDocumentCount\x12_\n\x14object_and_documents\x18\x01 \x03(\x0b\x32\x41.documents.ResponseGetObjectDocumentCount.ObjectAndDocumentsEntry\x1a\x39\n\x17ObjectAndDocumentsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\x85\x01\n\x10\x44ocumentInformer\x12q\n\x16GetObjectDocumentCount\x12(.documents.RequestGetObjectDocumentCount\x1a).documents.ResponseGetObjectDocumentCount\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'documents_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESPONSEGETOBJECTDOCUMENTCOUNT_OBJECTANDDOCUMENTSENTRY._options = None
  _RESPONSEGETOBJECTDOCUMENTCOUNT_OBJECTANDDOCUMENTSENTRY._serialized_options = b'8\001'
  _REQUESTGETOBJECTDOCUMENTCOUNT._serialized_start=30
  _REQUESTGETOBJECTDOCUMENTCOUNT._serialized_end=76
  _RESPONSEGETOBJECTDOCUMENTCOUNT._serialized_start=79
  _RESPONSEGETOBJECTDOCUMENTCOUNT._serialized_end=267
  _RESPONSEGETOBJECTDOCUMENTCOUNT_OBJECTANDDOCUMENTSENTRY._serialized_start=210
  _RESPONSEGETOBJECTDOCUMENTCOUNT_OBJECTANDDOCUMENTSENTRY._serialized_end=267
  _DOCUMENTINFORMER._serialized_start=270
  _DOCUMENTINFORMER._serialized_end=403
# @@protoc_insertion_point(module_scope)
