# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security_manager.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16security_manager.proto\x12\x10security_manager\"2\n\x17RequestPermissionsForMO\x12\x17\n\x0fget_permissions\x18\x01 \x01(\x08\"\xb7\x01\n\x0cMOPermission\x12\x0c\n\x04read\x18\x01 \x01(\x08\x12\x0e\n\x06update\x18\x02 \x01(\x08\x12\x0e\n\x06\x63reate\x18\x03 \x01(\x08\x12\x0e\n\x06\x64\x65lete\x18\x04 \x01(\x08\x12\x12\n\npermission\x18\x05 \x01(\t\x12\r\n\x05\x61\x64min\x18\x06 \x01(\x08\x12\x11\n\tparent_id\x18\x07 \x01(\x05\x12\x1a\n\x12root_permission_id\x18\x08 \x01(\x05\x12\x17\n\x0fpermission_name\x18\t \x01(\t\"G\n\rMOPermissions\x12\x36\n\x0emo_permissions\x18\x01 \x03(\x0b\x32\x1e.security_manager.MOPermission2}\n\x17SecurityManagerInformer\x12\x62\n\x10GetMOPermissions\x12).security_manager.RequestPermissionsForMO\x1a\x1f.security_manager.MOPermissions\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_manager_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTPERMISSIONSFORMO._serialized_start=44
  _REQUESTPERMISSIONSFORMO._serialized_end=94
  _MOPERMISSION._serialized_start=97
  _MOPERMISSION._serialized_end=280
  _MOPERMISSIONS._serialized_start=282
  _MOPERMISSIONS._serialized_end=353
  _SECURITYMANAGERINFORMER._serialized_start=355
  _SECURITYMANAGERINFORMER._serialized_end=480
# @@protoc_insertion_point(module_scope)
