# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import security_manager_pb2 as security__manager__pb2


class SecurityManagerInformerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMOPermissions = channel.unary_stream(
                '/security_manager.SecurityManagerInformer/GetMOPermissions',
                request_serializer=security__manager__pb2.RequestPermissionsForMO.SerializeToString,
                response_deserializer=security__manager__pb2.MOPermissions.FromString,
                )


class SecurityManagerInformerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMOPermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecurityManagerInformerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMOPermissions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMOPermissions,
                    request_deserializer=security__manager__pb2.RequestPermissionsForMO.FromString,
                    response_serializer=security__manager__pb2.MOPermissions.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'security_manager.SecurityManagerInformer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SecurityManagerInformer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMOPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/security_manager.SecurityManagerInformer/GetMOPermissions',
            security__manager__pb2.RequestPermissionsForMO.SerializeToString,
            security__manager__pb2.MOPermissions.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
