# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import graph_pb2 as graph__pb2


class GraphInformerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTMOTree = channel.unary_unary(
                '/graph.GraphInformer/GetTMOTree',
                request_serializer=graph__pb2.InTmoId.SerializeToString,
                response_deserializer=graph__pb2.OutGetTMOTree.FromString,
                )
        self.GetTPRMsByTMOid = channel.unary_unary(
                '/graph.GraphInformer/GetTPRMsByTMOid',
                request_serializer=graph__pb2.InTmoIds.SerializeToString,
                response_deserializer=graph__pb2.OutTprms.FromString,
                )
        self.GetMOsByTMOid = channel.unary_stream(
                '/graph.GraphInformer/GetMOsByTMOid',
                request_serializer=graph__pb2.InMOsByTMOid.SerializeToString,
                response_deserializer=graph__pb2.OutMOsStream.FromString,
                )
        self.GetMOsByTMOidPages = channel.unary_unary(
                '/graph.GraphInformer/GetMOsByTMOidPages',
                request_serializer=graph__pb2.InMOsByTMOid.SerializeToString,
                response_deserializer=graph__pb2.OutMOsStream.FromString,
                )
        self.GetTmoByMoId = channel.unary_unary(
                '/graph.GraphInformer/GetTmoByMoId',
                request_serializer=graph__pb2.InTmoByMoId.SerializeToString,
                response_deserializer=graph__pb2.OutTmoId.FromString,
                )
        self.GetMOsByMoIds = channel.unary_unary(
                '/graph.GraphInformer/GetMOsByMoIds',
                request_serializer=graph__pb2.InMOsByMoIds.SerializeToString,
                response_deserializer=graph__pb2.OutMOsByMoIds.FromString,
                )
        self.GetPRMsByPRMIds = channel.unary_unary(
                '/graph.GraphInformer/GetPRMsByPRMIds',
                request_serializer=graph__pb2.InPRMsByPRMIds.SerializeToString,
                response_deserializer=graph__pb2.OutPRMsByPRMIds.FromString,
                )
        self.GetPointTmoConst = channel.unary_unary(
                '/graph.GraphInformer/GetPointTmoConst',
                request_serializer=graph__pb2.InTmoId.SerializeToString,
                response_deserializer=graph__pb2.OutTmoIds.FromString,
                )
        self.GetTprmConst = channel.unary_unary(
                '/graph.GraphInformer/GetTprmConst',
                request_serializer=graph__pb2.InTprmId.SerializeToString,
                response_deserializer=graph__pb2.OutTmoIds.FromString,
                )
        self.GetTprmByTprmIds = channel.unary_unary(
                '/graph.GraphInformer/GetTprmByTprmIds',
                request_serializer=graph__pb2.InTprmIds.SerializeToString,
                response_deserializer=graph__pb2.OutTprms.FromString,
                )


class GraphInformerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTMOTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPRMsByTMOid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOsByTMOid(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOsByTMOidPages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTmoByMoId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOsByMoIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPRMsByPRMIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPointTmoConst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTprmConst(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTprmByTprmIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphInformerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTMOTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTMOTree,
                    request_deserializer=graph__pb2.InTmoId.FromString,
                    response_serializer=graph__pb2.OutGetTMOTree.SerializeToString,
            ),
            'GetTPRMsByTMOid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTPRMsByTMOid,
                    request_deserializer=graph__pb2.InTmoIds.FromString,
                    response_serializer=graph__pb2.OutTprms.SerializeToString,
            ),
            'GetMOsByTMOid': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMOsByTMOid,
                    request_deserializer=graph__pb2.InMOsByTMOid.FromString,
                    response_serializer=graph__pb2.OutMOsStream.SerializeToString,
            ),
            'GetMOsByTMOidPages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMOsByTMOidPages,
                    request_deserializer=graph__pb2.InMOsByTMOid.FromString,
                    response_serializer=graph__pb2.OutMOsStream.SerializeToString,
            ),
            'GetTmoByMoId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTmoByMoId,
                    request_deserializer=graph__pb2.InTmoByMoId.FromString,
                    response_serializer=graph__pb2.OutTmoId.SerializeToString,
            ),
            'GetMOsByMoIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMOsByMoIds,
                    request_deserializer=graph__pb2.InMOsByMoIds.FromString,
                    response_serializer=graph__pb2.OutMOsByMoIds.SerializeToString,
            ),
            'GetPRMsByPRMIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPRMsByPRMIds,
                    request_deserializer=graph__pb2.InPRMsByPRMIds.FromString,
                    response_serializer=graph__pb2.OutPRMsByPRMIds.SerializeToString,
            ),
            'GetPointTmoConst': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPointTmoConst,
                    request_deserializer=graph__pb2.InTmoId.FromString,
                    response_serializer=graph__pb2.OutTmoIds.SerializeToString,
            ),
            'GetTprmConst': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTprmConst,
                    request_deserializer=graph__pb2.InTprmId.FromString,
                    response_serializer=graph__pb2.OutTmoIds.SerializeToString,
            ),
            'GetTprmByTprmIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTprmByTprmIds,
                    request_deserializer=graph__pb2.InTprmIds.FromString,
                    response_serializer=graph__pb2.OutTprms.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graph.GraphInformer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraphInformer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTMOTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetTMOTree',
            graph__pb2.InTmoId.SerializeToString,
            graph__pb2.OutGetTMOTree.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPRMsByTMOid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetTPRMsByTMOid',
            graph__pb2.InTmoIds.SerializeToString,
            graph__pb2.OutTprms.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOsByTMOid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/graph.GraphInformer/GetMOsByTMOid',
            graph__pb2.InMOsByTMOid.SerializeToString,
            graph__pb2.OutMOsStream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOsByTMOidPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetMOsByTMOidPages',
            graph__pb2.InMOsByTMOid.SerializeToString,
            graph__pb2.OutMOsStream.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTmoByMoId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetTmoByMoId',
            graph__pb2.InTmoByMoId.SerializeToString,
            graph__pb2.OutTmoId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOsByMoIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetMOsByMoIds',
            graph__pb2.InMOsByMoIds.SerializeToString,
            graph__pb2.OutMOsByMoIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPRMsByPRMIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetPRMsByPRMIds',
            graph__pb2.InPRMsByPRMIds.SerializeToString,
            graph__pb2.OutPRMsByPRMIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPointTmoConst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetPointTmoConst',
            graph__pb2.InTmoId.SerializeToString,
            graph__pb2.OutTmoIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTprmConst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetTprmConst',
            graph__pb2.InTprmId.SerializeToString,
            graph__pb2.OutTmoIds.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTprmByTprmIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graph.GraphInformer/GetTprmByTprmIds',
            graph__pb2.InTprmIds.SerializeToString,
            graph__pb2.OutTprms.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
